### ISSUE TITLE
packet size don't work

### ISSUE THREAD

**Issue by RConTRS** [ACGaming/UniversalTweaks#444]
when i try to craft certain items in refined storage crafting grid using JEI add button, it kicks me out of my world with the error "payload may not be larger than 32727 bytes" although the mod has it's default packet size of 16777216 applied

here's the log, this is just me getting in my world, trying to craft a piston that way, and getting kicked

[log.txt](https://github.com/ACGaming/UniversalTweaks/files/15015432/log.txt)

also i don't have randompatches installed

**Comment by ACGaming** [comment]
Might get fixed by ffc316e56d6ed353f8daad86cd7647c7c6061135

**Comment by Lodgercat** [comment]
I was redirected here from Curseforge to post my logs with the same issue. Seems to happen with recipes involving planks in the crafting grid added via JEI like the OP said (I have biomes o plenty and forestry so there's a lot of planks). I do have random patches installed and both that and UT configs have been set to their max bytes on both client and server

Client log: 
[latest.log](https://github.com/user-attachments/files/16263153/latest.log)

Server Log:
[latest.log](https://github.com/user-attachments/files/16263159/latest.log)

Thank you for your time

**Comment by ACGaming** [comment]
This appears to be the same issue indeed. Can you also try to test again with [this test build](https://github.com/ACGaming/UniversalTweaks/actions/runs/9960030491/artifacts/1707041124)? Make sure to extract the archive and use the Universal Tweaks jar without `-dev` or `-sources`.

**Comment by Lodgercat** [comment]
Just checking if that's the right link as the version I was using had the same name as the linked one. I replaced both the client and server mods with the linked one but till getting the same error unfortunately. My UT packet size in the config is set to 2147483647 if that's making any difference.

Client log:
[latest.log](https://github.com/user-attachments/files/16274753/latest.log)

Server log:
[latest.log](https://github.com/user-attachments/files/16274756/latest.log)

**Comment by ACGaming** [comment]
Thanks for the provided logs, really helping out here!

I've updated the code injections and got a [new test build](https://github.com/ACGaming/UniversalTweaks/actions/runs/9993767455/artifacts/1715592835), same procedure.

Feel free to test and report back!

**Comment by Lodgercat** [comment]
No luck I'm afraid. Still saying 32727 bytes in the logs. I double checked what caused it to crash and wooden logs doesn't crash it so it seems to just be wooden planks. Happy to help as your mod is like glue sticking my modpack together so I appreciate your work.

Client log:
[latest.log](https://github.com/user-attachments/files/16285458/latest.log)

Server log:
[latest.log](https://github.com/user-attachments/files/16285462/latest.log)

**Comment by Lodgercat** [comment]
Great spot as now it's working after checking the config for it. I also didn't have Mclib on my server (only client) so I guess I deleted it from the server when it didn't work before asking you for help. Do you think this issue would have been resolved with one of your previous test versions if I had sorted Mclib? Can I still download an earlier version to test or not much point?

**Comment by Lodgercat** [comment]
Just tested it with my non-test server and client with the release version of UT 1.12 (from 5 days ago) and Mclib config matching the UT bytes config and it worked there too. So maybe it did just need to be the same with McLib?

Is it possible to change UT to enforce the bytes changes or do I need to keep McLib? Thanks for the help too :)

**Comment by ACGaming** [comment]
You'll either need the release version of Universal Tweaks (1.12.0) alongside McLib or the latest test build of Universal Tweaks alone to get it working as of now.

**Comment by RConTRS** [comment]
my game crashed after trying to craft a colossal chest interface with refined storage, u can see the payload issue still exist

[05:59:00] [Client thread/WARN]: Recipe registry plugin is slow, took 26.90 ms. class binnie.extratrees.integration.jei.multifence.MultiFenceRecipeRegistryPlugin
[05:59:00] [Client thread/INFO]: Transforming : mezz/jei/gui/recipes/RecipeTransferButtoninit(Lnet/minecraft/inventory/Container;Lnet/minecraft/entity/player/EntityPlayer;)V
[05:59:06] [Client thread/ERROR]: Could not load material model tconstruct:parts/tough_tool_rod.tmat#inventory
[05:59:14] [Client thread/ERROR]: Could not load material model tcomplement:parts/chisel_head.tmat#inventory
[05:59:15] [Client thread/ERROR]: Could not load material model tconstruct:parts/sharpening_kit.tmat#inventory
[05:59:16] [Client thread/ERROR]: Could not load material model tconstruct:parts/shard.tmat#inventory
[05:59:17] [Client thread/ERROR]: Could not load material model tconstruct:parts/tool_rod.tmat#inventory
[06:00:26] [Netty Local Client IO #0/ERROR]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[lh.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:533) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) [DefaultEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[06:00:26] [Client thread/INFO]: Cleaning 0 textures from VRAM
[06:00:26] [Netty Local Client IO #0/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[06:00:26] [Client thread/INFO]: Interrupting 0 image download threads
[06:00:26] [Netty Local Client IO #0/INFO]: FluxNetworkData has been unloaded
[06:00:26] [Netty Local Client IO #0/INFO]: Client disconnected from server
[06:00:26] [Netty Local Client IO #0/INFO]: UTDimensionManager ::: Cleaning up RFTools dimensions for the clientInstance
[06:00:26] [Netty Local Client IO #0/INFO]: Cleaning up RFTools dimensions
[06:00:26] [Netty Local Client IO #0/INFO]: Cleaning client cache...
[06:00:26] [Server thread/INFO]: FluxNetworkData has been successfully loaded
[06:00:26] [Netty Local Client IO #0/INFO]: Cleared cached client data! Disconnected from server.
[06:00:26] [Server thread/INFO]: RConTRS lost connection: Disconnected
[06:00:26] [Server thread/INFO]: RConTRS left the game
[06:00:26] [Client thread/INFO]: Mapping halted in E:\Games\Minecraft\Modpacks\My Modpacks\Classitech\journeymap\data\sp\World\DIM0
[06:00:26] [Server thread/INFO]: Stopping singleplayer server as player logged out
[06:00:27] [Server thread/INFO]: [lain.mods.cos.InventoryManager:onServerStopping:234]: Server is stopping... force saving all loaded CosmeticArmor data.
[06:00:27] [Server thread/INFO]: [lain.mods.cos.InventoryManager:onServerStopping:237]: 1ab02b18-73f7-3701-861d-387e0e9cbcdb
[06:00:27] [Server thread/INFO]: Stopping threads
[06:00:27] [Server thread/INFO]: Stopping server
[06:00:27] [Server thread/INFO]: Saving players
[06:00:27] [Server thread/INFO]: Saving worlds
[06:00:27] [Server thread/INFO]: Saving chunks for level 'World'/overworld
[06:00:27] [Server thread/INFO]: Saving chunks for level 'World'/ExtraUtils2_Quarry_Dim
[06:00:27] [Server thread/INFO]: Saving chunks for level 'World'/Spectre
[06:00:27] [Server thread/INFO]: Saving chunks for level 'World'/Storage Cell
[06:00:27] [Server thread/INFO]: Removing aura cache for world 0
[06:00:27] [Server thread/INFO]: Removing aura cache for world -9999
[06:00:27] [Server thread/INFO]: Removing aura cache for world -343800852
[06:00:27] [Server thread/INFO]: Removing aura cache for world 2
[06:00:27] [Server thread/INFO]: Unloading dimension 0
[06:00:27] [Server thread/INFO]: Unloading dimension -9999
[06:00:27] [Server thread/INFO]: Unloading dimension -343800852
[06:00:27] [Server thread/INFO]: Unloading dimension 2
[06:00:27] [Thread-66/WARN]: No auras found!
[06:00:27] [Thread-68/WARN]: No auras found!
[06:00:27] [Thread-67/WARN]: No auras found!
[06:00:27] [Thread-57/WARN]: No auras found!
[06:00:27] [Thread-68/INFO]: Stopping aura thread for dim 2
[06:00:27] [Thread-67/INFO]: Stopping aura thread for dim -343800852
[06:00:27] [Thread-57/INFO]: Stopping aura thread for dim 0
[06:00:27] [Thread-66/INFO]: Stopping aura thread for dim -9999
[06:00:30] [Server thread/INFO]: Applying holder lookups
[06:00:30] [Server thread/INFO]: Holder lookups applied
[06:00:30] [Server thread/INFO]: Unloaded WorldData!
[06:00:30] [Server thread/INFO]: Cleaning up all world data: 5 data blobs
[06:00:30] [Server thread/INFO]: Unloading EnderTank Data
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -13
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -20
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -15
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -16
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -17
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -18
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -19
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -21
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -22
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -29
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -30
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -31
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1504
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1501
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1500
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1503
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1502
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1505
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1506
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1507
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1508
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1509
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1510
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -1511
[06:00:30] [Server thread/INFO]: Unregistered Dimension: -28
[06:00:30] [Server thread/INFO]: FluxNetworkData has been unloaded
[06:00:30] [Server thread/INFO]: RFTools Dimensions: server is stopping. Shutting down gracefully

**Comment by ACGaming** [comment]
Were you using the latest test build or the release version of Universal Tweaks? Extended packet size tweak functionality is coming with the next release.

**Comment by RConTRS** [comment]
Ye im using latest, i thought it was fixed a while ago
